"""Validate the batched torch encoder against the banked CPU oracle.

WHY: `src/encoders/taxel_torch.py` is a rewrite of the supervisor's
`VirtualTaxelSensor` — a different language, a different memory layout, and a
different loop structure. Every one of those is an opportunity to change the
answer while still producing plausible-looking forces on plausible-looking
taxels, which is the failure mode this whole line of work is guarding against
(PROJECT_LOG §1.5b/§1.5d). So the torch version is checked frame-by-frame
against `explore/out/oracle_fixture.npz`, which stores the reference encoder's
*inputs* alongside its 368x3 outputs — no MuJoCo stepping required, and hence no
exposure to the Warp-vs-CPU contact discrepancy.

Two things are checked, not one:
  1. per-frame (B=1) agreement with the oracle, including the ncon=0 frames,
     which must give exact zeros rather than NaN from a 0/0 normalisation;
  2. all 30 frames stacked into one padded B=30 batch giving the same answer as
     running them one at a time — the actual claim the batching makes.

The reference accumulates in float64 and casts to float32 at the end; this runs
in float32 throughout, so agreement is to float32 rounding. The test reports the
achieved error rather than pretending to a tolerance it derived from nothing,
and asserts only a loose bound well above the observed value.

TWO FIXTURES, not one. `oracle_fixture.npz` was generated by a crude scripted
motion (all actuators to 60% of range) and only ever lights 37 of the 368
taxels — 31 of them on the palm, 2 on a fingertip. A bug confined to the
fingertip path would pass it. `oracle_fixture_v2.npz` (see
`explore/05_grasp_motions.py`) drives the hand through seven purpose-built grasp
patterns from varied cube poses and reaches 176 taxels including all four
fingertips, so both are checked and the per-body error is reported separately
for the fingertip group — a max over all 368 taxels is exactly where a
fingertip-only discrepancy would hide.

WHY v2 CARRIES A LOOSER float32 BOUND — read this before touching the tolerance.
The wider fixture exposes something the old one never hit. The reference gates
each contact's splat with two HARD thresholds:

    weights[dist_sq > cutoff**2] = 0        # in-plane
    weights[|local_z| > cutoff]  = 0        # patch locality

and then normalises by the surviving weight sum. In this scene the palm taxel
plane sits at |local_z| = 10.0000 mm from the cube contact plane, and
`kernel_cutoff` is 0.01 m — the taxels are sitting EXACTLY on the gate, with
measured margins of 0.0 to 0.2 micrometres. float32 cannot resolve that: a taxel
lands on one side of the gate for the float64 reference and the other side for a
float32 implementation. Because the surviving weights are renormalised, gaining
or losing ONE taxel out of a 2-5 taxel splat rescales all the others, which is
why the error is a clean ~4.6% RELATIVE across all three channels at once rather
than noise.

Measured, per-frame, over `oracle_fixture_v2.npz`:

    float32   max abs 1.26e-03   max rel 4.59e-02
    float64   max abs 4.16e-07   max rel 5.91e-08     <- fixture is stored float32

So the torch encoder is not wrong; the encoder's SEMANTICS are discontinuous and
this scene sits on the discontinuity. The test therefore asserts two things: a
tight float64 bound, which is the actual semantic-equivalence claim and would
still catch a real bug, and a loose float32 bound that admits the gate flip. Do
not tighten the float32 bound without re-checking the float64 one — and if the
float64 error ever rises above ~1e-6, that IS a real bug, whatever float32 says.

Run (memory-capped as everything on this box must be — unified memory means an
oversized allocation takes down the host, not the process, PROJECT_LOG §1.1):

    PYTHONPATH=third_party/leapXELA_model:explore \
      systemd-run --user --scope -q -p MemoryMax=16G -p MemorySwapMax=0 \
      .venv/bin/python tests/test_encoder_oracle.py
"""

from __future__ import annotations

import importlib.util
import os
import pathlib
import sys

os.environ.setdefault("MUJOCO_GL", "egl")

import numpy as np
import pytest
import torch

ROOT = pathlib.Path(__file__).resolve().parent.parent
for extra in (ROOT / "src", ROOT / "explore", ROOT / "third_party" / "leapXELA_model"):
    if str(extra) not in sys.path:
        sys.path.insert(0, str(extra))

from encoders.taxel_torch import (  # noqa: E402
    contact_inputs_from_geoms,
    encode_taxels,
    prepare_static,
)
from leapxela.taxel_layout import build_layout  # noqa: E402
from taxel_map import SUSPECT, remap_layout  # noqa: E402

FIXTURES = {
    "v1": ROOT / "explore" / "out" / "oracle_fixture.npz",       # 04_run_encoder.py
    "v2": ROOT / "explore" / "out" / "oracle_fixture_v2.npz",    # 05_grasp_motions.py
}
CHANNELS = ("shear_x", "shear_y", "normal_z")

# float32 bounds. v1's contacts happen to sit clear of the splat gates, so it
# holds the original tight bound; v2 sits exactly on the out-of-plane gate (see
# the module docstring) and 1.26e-3 is the measured gate-flip error, not noise.
ABS_TOL = {"v1": 1e-4, "v2": 5e-3}
# float64 bound — the real semantic-equivalence claim, tight for both fixtures.
# The fixture stores taxels as float32, so ~1e-7 is the floor.
F64_ABS_TOL = 1e-6
BATCH_TOL = 1e-6        # per-frame vs batched: same maths, different padding


def _load_run_encoder():
    """Import explore/04_run_encoder.py by path — its name is not an identifier.

    Reusing its `build_model`/`cube_geom_names` rather than copying them is the
    point: the fixture was produced by *that* model, and a silently divergent
    rebuild here would invalidate the comparison.
    """
    path = ROOT / "explore" / "04_run_encoder.py"
    spec = importlib.util.spec_from_file_location("run_encoder_ref", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _fingertip_taxels() -> np.ndarray:
    """Boolean mask over the 368 taxels selecting the four fingertip bodies.

    `taxel_map.SUSPECT` is the set of tactile-lineage bodies whose RL counterpart
    is a physically different, ~10 mm longer part — the least certain placement
    in the system, and the group a fingertip-only bug would live in.
    """
    return np.array([e.body in SUSPECT for e in build_layout().entries])


def _build_inputs(fixture: pathlib.Path):
    """Fixture + model -> per-frame numpy inputs for the batched encoder."""
    ref = _load_run_encoder()
    model = ref.build_model()
    layout = remap_layout(build_layout())
    static = prepare_static(model, layout, ref.cube_geom_names(model))

    npz = np.load(fixture)
    n_frames = int(npz["n_frames"])
    frames = []
    for i in range(n_frames):
        p = f"f{i:03d}_"
        ncon = int(npz[p + "ncon"])
        geom1 = npz[p + "contact_geom1"].astype(np.int64)
        geom2 = npz[p + "contact_geom2"].astype(np.int64)
        body, sign, valid = contact_inputs_from_geoms(static, geom1, geom2)
        frames.append(
            dict(
                ncon=ncon,
                contact_pos=npz[p + "contact_pos"].reshape(ncon, 3),
                contact_frame=npz[p + "contact_frame"].reshape(ncon, 3, 3),
                contact_force=npz[p + "contact_force"].reshape(ncon, 6),
                contact_body=body,
                contact_sign=sign,
                contact_valid=valid,
                # site_xpos/site_xmat are stored for ALL model sites (436 of
                # them); the taxels are the 368 the layout named.
                site_pos=npz[p + "site_xpos"][static.site_ids],
                site_mat=npz[p + "site_xmat"][static.site_ids].reshape(-1, 3, 3),
                taxels=npz[p + "taxels"],
            )
        )
    return static, frames, float(npz["kernel_sigma"]), float(npz["kernel_cutoff"])


def _t(x, dtype=torch.float32):
    return torch.as_tensor(np.ascontiguousarray(x), dtype=dtype)


def _encode_one(f, taxel_body, sigma, cutoff, dtype=torch.float32):
    """Single frame as a batch of one, in the requested precision.

    `dtype` is a parameter because float32-vs-float64 is the whole story on the
    v2 fixture: the encoder's splat gates are hard thresholds and this scene puts
    taxels exactly on one of them (module docstring).
    """
    return encode_taxels(
        contact_pos=_t(f["contact_pos"], dtype).unsqueeze(0),
        contact_frame=_t(f["contact_frame"], dtype).unsqueeze(0),
        contact_force=_t(f["contact_force"], dtype).unsqueeze(0),
        contact_sign=_t(f["contact_sign"], dtype).unsqueeze(0),
        contact_body=_t(f["contact_body"], torch.int64).unsqueeze(0),
        contact_valid=_t(f["contact_valid"], torch.bool).unsqueeze(0),
        site_pos=_t(f["site_pos"], dtype).unsqueeze(0),
        site_mat=_t(f["site_mat"], dtype).unsqueeze(0),
        taxel_body=taxel_body,
        kernel_sigma=sigma,
        kernel_cutoff=cutoff,
    )[0]


def _encode_batched(frames, taxel_body, sigma, cutoff):
    """All frames as one padded (B, C, ...) batch, C = max ncon."""
    B = len(frames)
    C = max(1, max(f["ncon"] for f in frames))
    pos = np.zeros((B, C, 3))
    frame = np.zeros((B, C, 3, 3))
    force = np.zeros((B, C, 6))
    sign = np.zeros((B, C))
    body = np.full((B, C), -1, dtype=np.int64)
    valid = np.zeros((B, C), dtype=bool)
    site_pos = np.stack([f["site_pos"] for f in frames])
    site_mat = np.stack([f["site_mat"] for f in frames])
    for b, f in enumerate(frames):
        n = f["ncon"]
        if n == 0:
            continue
        pos[b, :n] = f["contact_pos"]
        frame[b, :n] = f["contact_frame"]
        force[b, :n] = f["contact_force"]
        sign[b, :n] = f["contact_sign"]
        body[b, :n] = f["contact_body"]
        valid[b, :n] = f["contact_valid"]
    return encode_taxels(
        contact_pos=_t(pos),
        contact_frame=_t(frame),
        contact_force=_t(force),
        contact_sign=_t(sign),
        contact_body=_t(body, torch.int64),
        contact_valid=_t(valid, torch.bool),
        site_pos=_t(site_pos),
        site_mat=_t(site_mat),
        taxel_body=taxel_body,
        kernel_sigma=sigma,
        kernel_cutoff=cutoff,
    )


def _errors(got: np.ndarray, ref: np.ndarray):
    """Max abs and max relative error per channel over the flattened frames."""
    diff = np.abs(got - ref)
    abs_err = diff.reshape(-1, 3).max(axis=0)
    # Relative error is only meaningful where the reference is non-trivial; most
    # of the 368 taxels are exactly zero in every frame.
    ref_mag = np.abs(ref).reshape(-1, 3)
    d = diff.reshape(-1, 3)
    rel_err = np.zeros(3)
    for c in range(3):
        live = ref_mag[:, c] > 1e-6
        rel_err[c] = (d[live, c] / ref_mag[live, c]).max() if live.any() else 0.0
    return abs_err, rel_err


@pytest.mark.parametrize("version", sorted(FIXTURES))
def test_encoder_matches_oracle(version: str):
    fixture = FIXTURES[version]
    assert fixture.exists(), (
        f"{fixture} missing — regenerate it with "
        f"explore/{'04_run_encoder' if version == 'v1' else '05_grasp_motions'}.py"
    )
    static, frames, sigma, cutoff = _build_inputs(fixture)
    taxel_body = torch.as_tensor(static.taxel_body, dtype=torch.int64)

    per_frame = np.stack([_encode_one(f, taxel_body, sigma, cutoff).numpy() for f in frames])
    ref = np.stack([f["taxels"] for f in frames])
    batched = _encode_batched(frames, taxel_body, sigma, cutoff).numpy()

    assert not np.isnan(per_frame).any(), "NaN in per-frame output"
    assert not np.isnan(batched).any(), "NaN in batched output"

    abs_err, rel_err = _errors(per_frame, ref)
    b_abs, b_rel = _errors(batched, ref)
    batch_delta = np.abs(batched - per_frame).reshape(-1, 3).max(axis=0)

    empty = [i for i, f in enumerate(frames) if f["ncon"] == 0]
    nonempty = [i for i, f in enumerate(frames) if f["ncon"] > 0]
    live = (np.linalg.norm(ref, axis=2) > 1e-6).any(axis=0)
    tip = _fingertip_taxels()

    print(f"\noracle {version} ({fixture.name}): {len(frames)} frames, "
          f"{ref.shape[1]} taxels, sigma={sigma}, cutoff={cutoff}")
    print(f"  ncon==0 frames: {len(empty)} of {len(frames)}"
          + (f" {empty}" if len(empty) <= 12 else ""))
    print(f"  taxels ever active: {live.sum()}/{len(live)} "
          f"({(live & tip).sum()}/{tip.sum()} of them on fingertips)")
    print(f"  peak |ref| per channel: "
          + "  ".join(f"{c}={np.abs(ref[..., k]).max():.4f}" for k, c in enumerate(CHANNELS)))
    print(f"\n{'channel':<10}{'max abs err':>14}{'max rel err':>14}"
          f"{'batched abs':>14}{'batched rel':>14}{'batch-vs-1':>13}")
    for k, name in enumerate(CHANNELS):
        print(f"{name:<10}{abs_err[k]:>14.3e}{rel_err[k]:>14.3e}"
              f"{b_abs[k]:>14.3e}{b_rel[k]:>14.3e}{batch_delta[k]:>13.3e}")

    # FINGERTIPS SEPARATELY. The 136 fingertip taxels sit on the one body whose
    # geometry differs between the tactile and RL lineages, and a max over all
    # 368 taxels is dominated by the palm — which is why the old fixture could
    # not have caught a fingertip-only bug at all.
    if (live & tip).any():
        t_abs, t_rel = _errors(per_frame[:, tip], ref[:, tip])
        print(f"  fingertip taxels only ({tip.sum()} taxels, "
              f"{(live & tip).sum()} ever active): "
              + "  ".join(f"{c} abs={t_abs[k]:.3e} rel={t_rel[k]:.3e}"
                          for k, c in enumerate(CHANNELS)))
        assert t_abs.max() < ABS_TOL[version], \
            f"fingertip abs error {t_abs} exceeds {ABS_TOL[version]}"

    # THE SEMANTIC CLAIM, in float64. The float32 numbers above are contaminated
    # by the splat-gate flip described in the module docstring; run the identical
    # code in float64 and the disagreement must collapse to the fixture's own
    # float32 storage precision. If it does not, something is actually wrong.
    f64 = np.stack([
        _encode_one(f, taxel_body, sigma, cutoff, torch.float64).numpy() for f in frames
    ])
    f64_abs, f64_rel = _errors(f64, ref.astype(np.float64))
    print(f"  float64 (semantic equivalence): max abs {f64_abs.max():.3e}   "
          f"max rel {f64_rel.max():.3e}")
    assert f64_abs.max() < F64_ABS_TOL, (
        f"float64 abs error {f64_abs} exceeds {F64_ABS_TOL} — this is a real "
        f"discrepancy, not a precision artefact"
    )

    # ncon == 0 must give exact zeros, not NaN from a 0/0 normalisation.
    for i in empty:
        assert np.array_equal(per_frame[i], np.zeros_like(per_frame[i])), \
            f"frame {i} has ncon=0 but non-zero output"
        assert np.array_equal(batched[i], np.zeros_like(batched[i])), \
            f"frame {i} (batched) has ncon=0 but non-zero output"
        assert np.array_equal(ref[i], np.zeros_like(ref[i])), \
            f"frame {i} oracle is not zero — fixture assumption broken"

    # Sanity: the fixture must actually exercise the encoder, or this test is
    # only proving that zero equals zero.
    assert nonempty, "fixture has no contact frames"
    assert np.abs(ref[nonempty]).max() > 1e-3, "fixture contains no real forces"

    tol = ABS_TOL[version]
    assert abs_err.max() < tol, f"per-frame abs error {abs_err} exceeds {tol}"
    assert b_abs.max() < tol, f"batched abs error {b_abs} exceeds {tol}"
    assert batch_delta.max() < BATCH_TOL, \
        f"batched result differs from per-frame by {batch_delta}"


if __name__ == "__main__":
    for _v in sorted(FIXTURES):
        test_encoder_matches_oracle(_v)
    print("\nOK")
